car/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = "shop.views.page_not_found_view"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('accounts/', include('accounts.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('storage_info/', include('storage_tire.urls')),
    path('new-tires/', include('new_tire.urls')),
    path('', include('shop.urls')),
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,
                            document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, 
                            document_root=settings.MEDIA_ROOT)

new_tire/urls.py
from django.contrib import admin
from django.urls import path
from .views import Home, TireDetail, UpdatePrice

app_name = 'tires'

urlpatterns = [
    path('update-price/update', UpdatePrice, name="update_price"),
    path('<str:slug>/', TireDetail, name='tire_detail'),
    path('', Home, name='new_tire'),
    #path('', Home.as_view(), name='new_tire'),
]

new_tire/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from simple_history.models import HistoricalRecords

# Create your models here.
class Width(models.Model):
    name = models.PositiveIntegerField(verbose_name='Width')

    class Meta:
        ordering = ['name', ]

    def __str__(self):
        return str(self.name)

class Height(models.Model):
    name = models.PositiveIntegerField()

    class Meta:
        ordering = ['name', ]

    def __str__(self):
        return str(self.name)

class Radius(models.Model):
    name = models.PositiveIntegerField()

    class Meta:
        ordering = ['name', ]

    def __str__(self):
        return str(self.name)

class Brand(models.Model):
    name = models.CharField(max_length=55)

    class Meta:
        ordering = ['name', ]

    def __str__(self):
        return str(self.name)

class Kind(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ['name', ]

    def __str__(self):
        return str(self.name)

class Season(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ['name', ]

    def __str__(self):
        return str(self.name)

class Tire(models.Model):

    width = models.ForeignKey(
        Width,
        on_delete=models.CASCADE,
        related_name='tire_width',
        verbose_name='Ширина',
        null=True,
        blank=True)

    height = models.ForeignKey(
        Height,
        on_delete=models.CASCADE,
        related_name='tire_height',
        verbose_name='Витсота',
        null=True,
        blank=True)

    radius = models.ForeignKey(
        Radius,
        on_delete=models.CASCADE,
        related_name='tire_radius',
        verbose_name='Радіус',
        null=True,
        blank=True)

    brand = models.ForeignKey(
        Brand,
        on_delete=models.CASCADE,
        related_name='tire_brand',
        verbose_name='Бренд',
        null=True,
        blank=True)

    description = models.CharField(max_length=255)

    kind = models.ForeignKey(
        Kind,
        on_delete=models.CASCADE,
        related_name='tire_kind',
        verbose_name='Тип',
        null=True,
        blank=True)

    season = models.ForeignKey(
        Season,
        on_delete=models.CASCADE,
        related_name='tire_season',
        verbose_name='Сезон',
        null=True,
        blank=True)

    country = models.CharField(max_length=55)

    year = models.CharField(max_length=55)

    in_stock = models.PositiveIntegerField()

    price_one = models.PositiveIntegerField()
    price_two = models.PositiveIntegerField()
    price_three = models.PositiveIntegerField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    slug = models.SlugField(
        max_length=300,
        db_index=True,
        unique=True,
        blank=True)

    articul = models.CharField(
        max_length=25,
        blank=True,
        null=True,
        verbose_name='Артикул')

    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        super(Tire, self).save()

        if not self.slug:
            self.slug = slugify(str(self.description).replace("/", "-") + '-' + str(self.brand) + '-' + str(self.id)).replace("/", "-")
            super(Tire, self).save(*args, **kwargs)
        
        if not self.articul:

            self.articul = '01-'+ str(self.id)

            super(Tire, self).save()

        # if not self.category_size:
        #     get_category = self.description
        #     get_category = get_category.split()
        #     self.category_size = Category.objects.get(size=get_category[0])
        #     super(Tire, self).save()



    def get_absolute_url(self):
        return reverse('tires:tire_detail', kwargs={"slug": self.slug})

    def __str__(self):
        return str(self.description)


class QuickOrderNewTire(models.Model):
    
    CHOICES = (
        ('-', '-'),
        ('Бронь', 'Бронь'),
        ('Не відповів', 'Не відповів'),
        ('Забрав', 'Забрав'),
        ('Відмова', 'Відмова'),
    )

    phone = models.IntegerField(verbose_name="телефон")
    tire = models.ForeignKey(Tire, related_name='quikoreder_new_tire', on_delete=models.CASCADE,  blank=True, null=True, verbose_name='ID шин')
    price = models.PositiveIntegerField(blank=True, null=True)
    status = models.CharField(max_length=50, choices=CHOICES, blank=True, null=True, default='-')
    client = models.ForeignKey(User, related_name='new_tire_client', on_delete=models.CASCADE, blank=True, null=True)
    # manager = models.ForeignKey(User, related_name='quick_order_user', on_delete=models.CASCADE, blank=True, null=True)
    complete = models.BooleanField(default=False, verbose_name='Виконаний')
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['complete']
        verbose_name = 'Швидке замовлення'
        verbose_name_plural = 'Швидкі замовлення'

    def __str__(self):
        return str(self.phone)

shop/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from simple_history.models import HistoricalRecords
# from django.db.models import deletion
# from django.db.models.fields import BLANK_CHOICE_DASH
from django.urls import reverse
from django.utils.safestring import mark_safe
from ckeditor.fields import RichTextField
from django.utils.text import slugify
import segno
from io import BytesIO
from django.core.files import File
from PIL import Image as IMG
from PIL import ImageDraw


class Season(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Сезон:')
    image_icon = models.ImageField(upload_to='season_icon', blank=True)
    description = RichTextField(null=True, blank=True, verbose_name='Опис сезону:')
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Сезон'
        verbose_name_plural = 'Сезон'

    def __str__(self):
        return self.name

    #def get_absolute_url(self):
    #    return reverse('shop:Season', args=[self.slug])

class Kind(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Тип:')
    image_icon = models.ImageField(upload_to='kind_icon', blank=True)
    description = RichTextField(null=True, blank=True, verbose_name='Опис:')
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Тип'
        verbose_name_plural = 'Тип'

    def __str__(self):
        return self.name

    #def get_absolute_url(self):
    #    return reverse('shop:Name', args=[self.slug])

class Brand(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Назва бренду:")
    image_icon = models.ImageField(upload_to='brand_icon', blank=True)
    description = RichTextField(null=True, blank=True, verbose_name='Опис бренду:')
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренди'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:brand_detail', kwargs={'slug': self.slug})

    #def get_absolute_url(self):
    #    return reverse('shop:TireListByCategory', args=[self.slug])

class BrandModel(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name='Модель:')

    brand = models.ForeignKey(
        Brand,
        related_name='brand_model',
        on_delete=models.CASCADE,
        verbose_name='Бренд моделі:')

    season = models.ForeignKey(
        Season,
        related_name='brand_model_season',
        on_delete=models.CASCADE,
        verbose_name='Сезон моделі')
        
    description = RichTextField(null=True, blank=True, verbose_name='Опис моделі:')
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Модель'
        verbose_name_plural = 'Модель'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:brand_model_detail', kwargs={'brand_slug': self.brand.slug, 'slug': self.slug})
    #def get_absolute_url(self):
    #    return reverse('shop:TireListByCategory', args=[self.slug])

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Категорія:')

    kind = models.ForeignKey(
        Kind,
        default=1,
        related_name='category_kind',
        on_delete=models.CASCADE,
        verbose_name='Тип категорії:')

    description = RichTextField(null=True, blank=True, verbose_name='Опис категорії:')
    slug = models.SlugField(unique=True)

    # SEO fields
    seo_title = models.CharField(max_length=64, blank=True, verbose_name="SEO Title")
    seo_description = models.TextField(blank=True, verbose_name='SEO Description')
    seo_keywords = models.CharField(max_length=120, blank=True, verbose_name='SEO Keywords')

    class Meta:
        ordering = ['name']
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:category_list', kwargs={'category_slug': self.slug})

class IndexSpeed(models.Model):
    name_one = models.CharField(max_length=2, unique=True, verbose_name='Індекс:')
    name_two = models.CharField(max_length=25, verbose_name='Значення:')

    class Meta:
        ordering = ['name_one']
        verbose_name = 'Індекс швидкості'
        verbose_name_plural = 'Індекси швидкості'

    def __str__(self):
        return self.name_one

class IndexLoad(models.Model):
    name_one = models.CharField(max_length=10, unique=True, verbose_name='Індекс:')
    name_two = models.CharField(max_length=25, verbose_name='Значення:')

    class Meta:
        ordering = ['name_one']
        verbose_name = 'Індекс навантаження'
        verbose_name_plural = 'Індекси навантаження'

    def __str__(self):
        return self.name_one

class Tire(models.Model):

    CHOICES = (
        ('-', '-'),
        ('Т', 'Т'),
        ('БК', 'БК'),
        ('КЛ', 'КЛ'),
        ('Л/П', 'Л/П'),
    )

    category = models.ForeignKey(
        Category,
        related_name='tire_category',
        on_delete=models.CASCADE,
        verbose_name='Категорія:')

    model = models.ForeignKey(
        BrandModel,
        related_name='tire_model',
        on_delete=models.CASCADE,
        verbose_name='Модель:')

    index_load = models.ForeignKey(
        IndexLoad,
        related_name='tire_index_load',
        on_delete=models.CASCADE,
        verbose_name='Індекс навантаження:')

    index_speed = models.ForeignKey(
        IndexSpeed,
        related_name='tire_index_speed',
        on_delete=models.CASCADE,
        verbose_name='Індекс швидкості:')

    condition = models.IntegerField(verbose_name='Стан:')
    year = models.IntegerField(verbose_name='Рік:', blank=True, null=True)
    country = models.CharField(max_length=150, verbose_name='Країна:', blank=True)
    in_stock = models.IntegerField(verbose_name='На складі, шт.:')
    available = models.BooleanField(default=True, verbose_name='В наявності:')

    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name='Вартість:')
    new_price = models.DecimalField(
        max_digits=5, decimal_places=2, null=True, blank=True, verbose_name='Нова вартість:')

    recommend = models.BooleanField(default=False, verbose_name='Рекомендуєм:')

    #additional properties
    shipy = models.BooleanField(default=False, verbose_name='Шипы')
    lipuchka = models.BooleanField(default=False, verbose_name='Липучка')
    run_flat = models.BooleanField(default=False, verbose_name='RunFlat')
    conti_seal = models.BooleanField(default=False, verbose_name='ContiSeal')
    low_prof = models.BooleanField(default=False, verbose_name='Низк.проф.')
    mad = models.BooleanField(default=False, verbose_name='Грязевые')
    rain = models.BooleanField(default=False, verbose_name='Дождевые')

    #for administrator
    choice = models.CharField(max_length=50, choices=CHOICES, blank=True, null=True)

    slug = models.SlugField(max_length=200, db_index=True, unique=True, blank=True)

    qr_code = models.ImageField(upload_to='qr_codes', blank=True, null=True, help_text="QR-code генерується автоматично")

    articul = models.CharField(max_length=25, blank=True, null=True, verbose_name='Артикул')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        super(Tire, self).save()
        if not self.slug:
            self.slug = slugify(self.category.slug) + '-' + str(self.model.brand) + '-' + str(self.model.slug) + '-' + str(self.id)
            super(Tire, self).save()

        if not self.articul:

            self.articul = '02-'+ str(self.id)

            super(Tire, self).save()

        if self.qr_code:
            pass
        else:
            qrcode = segno.make(f'https://car-plus.kyiv.ua/{self.category.slug}/{self.slug}/', error='l')
            out = BytesIO()
            qrcode.save(out, kind='png', dark='#000', light=None, scale=10)
            # qrcode.to_artistic(background='/car_env/media/LOGO-CAR.png', target=out, scale=40, kind='png')
            self.qr_code.save(f'{self.id}.png', File(out), save=False)

            super(Tire, self).save()


    def get_absolute_url(self):
        return reverse('shop:tire_detail', kwargs={'category_slug': self.category.slug, "slug": self.slug})

    def __str__(self):
        return str(self.category)+'-'+str(self.model)+'-'+str(self.model.brand.name)



class Image(models.Model):
    image = models.ImageField(upload_to='foto', verbose_name='Зображення:')
    tire = models.ForeignKey(
        Tire,
        default=False,
        on_delete=models.CASCADE,
        verbose_name='Резина:')

    class Meta:
        ordering = ['tire']
        verbose_name = 'Зображення'
        verbose_name_plural = 'Зображення'

    def image_url(self):
        return mark_safe(f'<img src="{self.image.url}" width="auto" height="250px"')


class QuickOrder(models.Model):
    
    CHOICES = (
        ('-', '-'),
        ('Бронь', 'Бронь'),
        ('Не відповів', 'Не відповів'),
        ('Забрав', 'Забрав'),
        ('Відмова', 'Відмова'),
    )

    phone = models.IntegerField(verbose_name="телефон")
    tire = models.ForeignKey(Tire, related_name='quikoreder_tire', on_delete=models.CASCADE,  blank=True, null=True, verbose_name='ID шин')

new_tire/forms.py
from django import forms
from .models import QuickOrderNewTire


class QuickOrderNewTireForm(forms.ModelForm):

    class Meta:
        model = QuickOrderNewTire
        fields = ('phone',)

        widgets={
            'phone':forms.TextInput(attrs={'placeholder':'прик.:0971234455', 'id':'inputTel', 'class':'form-control', 'type':'tel', 
            'pattern':'[0]{1}[4-9]{1}[3-9]{1}[0-9]{7}'}),
        }

templates/new_tire/new-tire-list.html
{% extends 'new_main.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}
<title>Нові шини від шинного центру Car+ - інтернет Магазин (КарПлюс)</title>



{% endblock title %}

{% block description %}

{% endblock description %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <h1>Нові шини {% if user.is_superuser %} <a href="/new-tires/update-price/update">Оновити прайс</a> {% endif %}</h1>
            <hr>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-xl-2 col-lg-3 col-md-4 col-sm-4 col-12 mb-4">
            <div class="container-fluid">
                <form methood="GET">
                    <div class="row">

                        <div class="col">
                            <div class="form-group">
                                <small id="id_description" class="form-text text-muted">Пошук за моделлю:</small>
                                {{ filter.form.description }}
                            </div>
                        </div>
                    
                        <div class="col">
                            <div class="form-group">
                                {{ filter.form.ordering }}
                            </div>
                        </div>

                        <div class="col">
                            <div class="form-group">
                                <!-- <label for="id_price_two__gt">{{ filter.form.price__gt.label_tag }}</label> -->
                                {{ filter.form.price__gt }}
                                <small id="id_price_two__gt" class="form-text text-muted">Вартість від:</small>
                            </div>
                        </div>

                        <div class="col">
                            <div class="form-group">
                                <!-- <label for="id_price_two__lt">{{ filter.form.price__gt.label_tag }}</label> -->
                                {{ filter.form.price__lt }}
                                <small id="id_price_two__lt" class="form-text text-muted">Вартість до:</small>
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="form-group">
                                <!-- <label for="id_price_two__lt">{{ filter.form.price__gt.label_tag }}</label> -->
                                {{ filter.form.brand }}
                                <small id="id_brand" class="form-text text-muted">Бренд:</small>
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="form-group">
                                <!-- <label for="id_price_two__lt">{{ filter.form.price__gt.label_tag }}</label> -->
                                {{ filter.form.width }}
                                <small id="id_width" class="form-text text-muted">Ширина:</small>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <!-- <label for="id_price_two__lt">{{ filter.form.price__gt.label_tag }}</label> -->
                                {{ filter.form.height }}
                                <small id="id_height" class="form-text text-muted">Висота:</small>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <!-- <label for="id_price_two__lt">{{ filter.form.price__gt.label_tag }}</label> -->
                                {{ filter.form.radius }}
                                <small id="id_radius" class="form-text text-muted">Радіус:</small>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <!-- <label for="id_price_two__lt">{{ filter.form.price__gt.label_tag }}</label> -->
                                {{ filter.form.season }}
                                <small id="id_season" class="form-text text-muted">Сезон:</small>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <!-- <label for="id_price_two__lt">{{ filter.form.price__gt.label_tag }}</label> -->
                                {{ filter.form.kind }}
                                <small id="id_kind" class="form-text text-muted">Тип:</small>
                            </div>
                        </div>

                        <button  class="btn btn-success" type="submit">Фільтрувати</button>
                    
                    </div>
                </form>
            </div>
        </div>
        <div class="col-xl-10 col-lg-9 col-md-8 col-sm-8 col-12 mb-4">

            <div class="container-fluid">
                <div class="row">
              
                  {% for tire in paginator_filter %}
              
                    {% if forloop.counter == 4 %}
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 col-12 mb-4 d-flex">
                        <img src="/media/ads-img/image-ads.png" alt="Знижка на шиномонтаж" title="Шиномонтаж акційна пропозиція" style="object-fit:contain;width:100%;">
                    </div>
                    {% endif %}
              
              
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 col-12 mb-4">
                        <div class="card d-flex">
                            <div class="picture-resize">
                              {% if tire.image %}
                                <img class="card-img card-img2" src="{% with tire.image_set.all|first as img %} {{ img.image.url }} {% endwith %}" alt="Шини б\у {{ tire.category }}">
                              {% else %}
                                <img class="card-img card-img2" src="/media/ads-img/new-car-tire.png" alt="Шини б\у {{ tire.category }}">
                              {% endif %}
                            </div>
                            <div class="card-img-overlay">
                                {% if tire.recommend %}
                                    <h5 class="card-recomend">Рекомендуємо</h5>
                                {% endif %}
                                <h5 class="card-delivery">Доставка 1-3 дні</h5>
                            </div>
                            <div class="col text-right card-icon mt-2 mb-3">
                                {% if tire.shipy %}
                                    <img src="{% static 'admin/img/icons/tire-ship.png' %}" alt="Під шип" title="Під шип">
                                {% endif %}
                                {% if tire.lipuchka %}
                                    <img src="{% static 'admin/img/icons/tire-ship.png' %}" alt="Липучка" title="Липучка">
                                {% endif %}
                                {% if tire.run_flat %}
                                    <img src="{% static 'admin/img/icons/mfs.png' %}" alt="RunFlat" title="RunFlat">
                                {% endif %}
                                {% if tire.conti_seal %}
                                    <img src="{% static 'admin/img/icons/contiseal.png' %}" alt="Автоліквідація проколів" title="Автоліквідація проколів">
                                {% endif %}
                                {% if tire.low_prof %}
                                    <img src="{% static 'admin/img/icons/runflat.png' %}" alt="Низький профіль" title="Низький профіль">
                                {% endif %}
                                {% if tire.mad %}
                                    <img src="{% static 'admin/img/icons/mad.png' %}" alt="Грязьові" title="Грязьові">
                                {% endif %}
                                {% if tire.rain %}
                                    <img src="{% static 'admin/img/icons/rain.png' %}" alt="Дождьові" title="Дождьові">
                                {% endif %}
              
                                {% if tire.kind.name == 'Легкові' %}
                                    <img src="{% static 'admin/img/icons/sedan.png' %}" alt="Легкові" title="Легкові">
                                {% elif tire.kind.name  == 'LT' %}
                                    <img src="{% static 'admin/img/icons/truck.png' %}" alt="Легкогрузові" title="Легкогрузові">
                                {% endif %}
              
                                {% if tire.season.name == 'літо' %}
                                    <img src="{% static 'admin/img/icons/sun.png' %}" alt="Літо" title="Літо">
                                {% elif tire.season.name == 'зима' %}
                                    <img src="{% static 'admin/img/icons/snowflake.png' %}" alt="Зима" title="Зима">
                                {% else %}
                                    <img src="{% static 'admin/img/icons/sun-winter.png' %}" alt="Всесезон" title="Всесезон">
                                {% endif %}
                            </div>
                            <div class="col brand-title">
                                <a href="{{ tire.get_absolute_url }}">{{ tire.description|upper }}<br>{{ tire.brand.name|truncatechars:20 }}</a> 
                                
                            </div>
                            <div class="col text-success">
                                    У наявності: {{ tire.in_stock }} шт
                            </div>
                            <div class="col card-address">
                                вул. Єдності, 94 (Троєщина-Погреби)<br>
                                Самовивіз на сьогодні
                            </div>
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-8">
                                        <span class="size bg-link">
                                            <a href="{{ tire.get_absolute_url }}">{{ tire.category }}</a> 
                                        </span>
                                        <span class="price bg-link">Самовивіз - &#8372;{{ tire.price_two|floatformat:0}}</span>
                                        <span class="price bg-link">Доставка - &#8372;{{ tire.price_three|floatformat:0}}</span>
                                    </div>
              
                                    <div class="col-4">
                                        <div class="trash-box">
                                            <a href="{{ tire.get_absolute_url}}#quick_order" rel=”nofollow”>
                                                <img src="{% static 'admin/img/icons/shopping-cart.png' %}" alt="Швидке замовлення" title="Швидке замовлення бу шин">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                  {% endfor %}
                </div>
              
                <div class="row">
                  <div class="col-md-12">
                                            {% if paginator_filter.has_other_pages %}</p>
                  <ul class="pagination">
                                              {% if paginator_filter.has_previous %}</p>
                  <li class="page-item">
                                                  <a href="?page={{paginator_filter.previous_page_number}}" class="page-link">«</a>
                                                </li>
                  <p>                            {% else%}</p>
                  <li class="page-item disabled"></li>
                  <p>                              <a class="page-link">«</a><br />
                                              {% endif %}<br />
                                              {% for i in paginator_filter.paginator.page_range %}<br />
                                                {% if paginator_filter.paginator.page_range %}<br />
                                                  {% if paginator_filter.number == i%}</p>
                  <li class="page-item active"><a  class="page-link">{{i}}</a></li>
                  <p>                                {% else %}</p>
                  <li class="page-item"><a  href="?page={{i}}" class="page-link">{{i}}</a></li>
                  <p>                                {% endif%}<br />
                                                {% endif %}<br />
                                              {% endfor %}<br />
                                              {% if paginator_filter.has_next %}</p>
                  <li class="page-item">
                                                <a href="?page={{paginator_filter.next_page_number}}" class="page-link">»</a>
                                              </li>
                  <p>                          {% else%}</p>
                  <li class="page-item disabled"></li>
                  <p>                            <a class="page-link">»</a><br />
                                            {% endif %}
                                            </ul>
                  <p>                          {% endif %}
                                          </p></div>
                  </p></div>
              </div>
        </div>
    </div>
</div>
{% endblock content %}